/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ValentinesProjectPackage;

import javax.swing.JOptionPane;

/**
 *
 * @author Me
 */
public class ValentinesProjectGUI extends javax.swing.JFrame {

    /**
     * Creates new form ValentinesProjectGUI
     */
    public ValentinesProjectGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGuessWhat = new javax.swing.JLabel();
        jTextFieldGuessWhat = new javax.swing.JTextField();
        jButtonGuess = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Valentines Day Gift");
        setBackground(new java.awt.Color(102, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.red);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelGuessWhat.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelGuessWhat.setForeground(new java.awt.Color(102, 102, 255));
        jLabelGuessWhat.setText("Guess What?");
        getContentPane().add(jLabelGuessWhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, -1));

        jTextFieldGuessWhat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldGuessWhat.setText(" ");
        jTextFieldGuessWhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGuessWhatActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldGuessWhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 120, -1));

        jButtonGuess.setText(" Guess");
        jButtonGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuessActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuess, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        setSize(new java.awt.Dimension(342, 255));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldGuessWhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGuessWhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGuessWhatActionPerformed

    private void jButtonGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuessActionPerformed
        if (jTextFieldGuessWhat.getText().equalsIgnoreCase("hello")) {
            JOptionPane.showMessageDialog(null, "First step.......");
        } else {
            JOptionPane.showMessageDialog(null, "You did not get it!!!!!!!");
           
        }
         jTextFieldGuessWhat.setText("");
    }//GEN-LAST:event_jButtonGuessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValentinesProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValentinesProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValentinesProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValentinesProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ValentinesProjectGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuess;
    private javax.swing.JLabel jLabelGuessWhat;
    private javax.swing.JTextField jTextFieldGuessWhat;
    // End of variables declaration//GEN-END:variables
}
